services:
  server:
    build:
      dockerfile: dockerfile
      context: ./server   
    ports: 
      - "3001:3001"
  front:
    build:
      dockerfile: dockerfile
      context: ./front
    ports: 
      - "5173:5173"